# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nguoidung', '0001_initial'),
        ('thuoc', '0001_initial'),
        ('lichhen', '0001_initial'),
        ('benhan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_phong', models.CharField(blank=True, max_length=50, unique=True)),
                ('ten_phong', models.CharField(max_length=255)),
                ('loai_phong', models.CharField(choices=[('TU_VAN', 'Tư vấn'), ('HOI_CHAN', 'Hội chẩn'), ('HEN_LICH', 'Hẹn lịch'), ('HOI_DAP', 'Hỏi đáp')], default='TU_VAN', max_length=20)),
                ('trang_thai', models.CharField(choices=[('MO', 'Mở'), ('DONG', 'Đóng'), ('KET_THUC', 'Kết thúc')], default='MO', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('ngay_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('bac_si', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phong_chat_bac_si', to='nguoidung.bacsi')),
                ('benh_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='benhan.hosobenhan')),
                ('benh_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phong_chat', to='nguoidung.benhnhan')),
                ('lich_hen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lichhen.lichhen')),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phong_chat_nhan_vien', to='nguoidung.nhanvien')),
            ],
            options={
                'verbose_name': 'Phòng chat',
                'verbose_name_plural': 'Phòng chat',
                'db_table': 'phong_chat',
                'ordering': ['-ngay_cap_nhat'],
            },
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loai', models.CharField(choices=[('TEXT', 'Van ban'), ('HINH_ANH', 'Hinh anh'), ('FILE', 'File'), ('THUOC', 'Thuoc'), ('LICH_HEN', 'Lich hen'), ('BENH_AN', 'Benh an'), ('THONG_BAO', 'Thong bao')], default='TEXT', max_length=20)),
                ('noi_dung', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/%d/')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/%d/')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('ngay_xem', models.DateTimeField(blank=True, null=True)),
                ('benh_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='benhan.hosobenhan')),
                ('lich_hen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lichhen.lichhen')),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_phong_gui', to=settings.AUTH_USER_MODEL)),
                ('phong_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='trochuyen.phongchat')),
                ('thuoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thuoc.thuoc')),
            ],
            options={
                'db_table': 'tin_nhan',
                'ordering': ['ngay_gui'],
            },
        ),
        migrations.CreateModel(
            name='ThanhVienPhong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vai_tro', models.CharField(choices=[('BENH_NHAN', 'Bệnh nhân'), ('BAC_SI', 'Bác sĩ'), ('NHAN_VIEN', 'Nhân viên')], max_length=20)),
                ('ngay_tham_gia', models.DateTimeField(auto_now_add=True)),
                ('ngay_roi_di', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phong_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_vien', to='trochuyen.phongchat')),
            ],
            options={
                'verbose_name': 'Thành viên phòng',
                'verbose_name_plural': 'Thành viên phòng',
                'db_table': 'thanh_vien_phong',
            },
        ),
        migrations.CreateModel(
            name='TinNhanDaXem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('da_xem_luc', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_da_xem', to=settings.AUTH_USER_MODEL)),
                ('tin_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trang_thai_xem', to='trochuyen.tinnhan')),
            ],
            options={
                'verbose_name': 'Trạng thái đọc tin nhắn',
                'verbose_name_plural': 'Trạng thái đọc tin nhắn',
                'db_table': 'tin_nhan_da_xem',
                'indexes': [models.Index(fields=['tin_nhan'], name='tin_nhan_da_tin_nha_2382e9_idx'), models.Index(fields=['nguoi_dung', 'da_xem_luc'], name='tin_nhan_da_nguoi_d_0d8a7e_idx')],
                'unique_together': {('tin_nhan', 'nguoi_dung')},
            },
        ),
        migrations.AddIndex(
            model_name='tinnhan',
            index=models.Index(fields=['phong_chat', 'ngay_gui'], name='tin_nhan_phong_c_414b20_idx'),
        ),
        migrations.AddIndex(
            model_name='thanhvienphong',
            index=models.Index(fields=['phong_chat', 'is_active'], name='thanh_vien__phong_c_1a7b2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thanhvienphong',
            unique_together={('phong_chat', 'nguoi_dung')},
        ),
        migrations.AddIndex(
            model_name='phongchat',
            index=models.Index(fields=['ma_phong'], name='phong_chat_ma_phon_b3a20c_idx'),
        ),
        migrations.AddIndex(
            model_name='phongchat',
            index=models.Index(fields=['benh_nhan', 'trang_thai'], name='phong_chat_benh_nh_528a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='phongchat',
            index=models.Index(fields=['ngay_cap_nhat'], name='phong_chat_ngay_ca_89e148_idx'),
        ),
    ]
