# Generated by Django 4.2.29 on 2026-04-20 06:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thuoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('so_luong', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('thue_suat', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('chiet_khau', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'chi_tiet_don_hang',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('ma_don_hang', models.CharField(max_length=50, unique=True)),
                ('ten_nguoi_nhan', models.CharField(max_length=100)),
                ('so_dien_thoai_nhan', models.CharField(max_length=15)),
                ('email_nhan', models.EmailField(blank=True, max_length=254)),
                ('dia_chi_giao_hang', models.TextField()),
                ('loai_don', models.CharField(choices=[('ONLINE', 'Mua online'), ('TAI_QUAY', 'Mua tại quầy')], default='ONLINE', max_length=20)),
                ('ngay_xu_ly', models.DateTimeField(blank=True, null=True)),
                ('tong_tien_hang', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('phi_ship', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('giam_gia', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('trang_thai', models.CharField(choices=[('MOI_TAO', 'Mới tạo'), ('CHO_THANH_TOAN', 'Chờ thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán'), ('DANG_CHUAN_BI', 'Đang chuẩn bị'), ('DANG_GIAO', 'Đang giao hàng'), ('HOAN_THANH', 'Hoàn thành'), ('DA_HUY', 'Đã hủy')], default='MOI_TAO', max_length=20)),
                ('ly_do_huy', models.TextField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True)),
                ('trang_thai_duyet_bs', models.CharField(choices=[('KHONG_CAN', 'Khong can duyet bac si'), ('CHO_DUYET', 'Cho bac si duyet thuoc dac thu'), ('DONG_Y', 'Dong y'), ('TU_CHOI', 'Tu choi')], default='KHONG_CAN', help_text='Duyệt mua thuốc cần đơn / tư vấn (can_don_thuoc, can_tu_van)', max_length=20)),
                ('ghi_chu_duyet_bs', models.TextField(blank=True)),
                ('ngay_duyet_bs', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'don_hang',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
                'db_table': 'gio_hang',
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('phuong_thuc', models.CharField(choices=[('TIEN_MAT', 'Tiền mặt'), ('CHUYEN_KHOAN', 'Chuyển khoản'), ('THE', 'Thẻ'), ('VI_DIEN_TU', 'Ví điện tử'), ('VNPAY', 'VNPay (QR / chuyển khoản ảo)')], max_length=20)),
                ('trang_thai', models.CharField(choices=[('CHO_XU_LY', 'Chờ xử lý'), ('THANH_CONG', 'Thành công'), ('THAT_BAI', 'Thất bại'), ('HOAN_TIEN', 'Hoàn tiền')], default='CHO_XU_LY', max_length=20)),
                ('ma_giao_dich', models.CharField(blank=True, max_length=100)),
                ('noi_dung', models.TextField(blank=True)),
                ('ngay_thanh_toan', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_toan', to='donhang.donhang')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'thanh_toan',
            },
        ),
        migrations.CreateModel(
            name='SanPhamGioHang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('so_luong', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('don_gia_tai_thoi_diem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham_gio_hang', to='donhang.giohang')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuoc.thuoc')),
            ],
            options={
                'verbose_name': 'Sản phẩm giỏ hàng',
                'verbose_name_plural': 'Sản phẩm giỏ hàng',
                'db_table': 'san_pham_gio_hang',
            },
        ),
        migrations.CreateModel(
            name='LichSuDonHang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trang_thai_cu', models.CharField(choices=[('MOI_TAO', 'Mới tạo'), ('CHO_THANH_TOAN', 'Chờ thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán'), ('DANG_CHUAN_BI', 'Đang chuẩn bị'), ('DANG_GIAO', 'Đang giao hàng'), ('HOAN_THANH', 'Hoàn thành'), ('DA_HUY', 'Đã hủy')], max_length=20)),
                ('trang_thai_moi', models.CharField(choices=[('MOI_TAO', 'Mới tạo'), ('CHO_THANH_TOAN', 'Chờ thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán'), ('DANG_CHUAN_BI', 'Đang chuẩn bị'), ('DANG_GIAO', 'Đang giao hàng'), ('HOAN_THANH', 'Hoàn thành'), ('DA_HUY', 'Đã hủy')], max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='donhang.donhang')),
            ],
            options={
                'verbose_name': 'Lịch sử đơn hàng',
                'verbose_name_plural': 'Lịch sử đơn hàng',
                'db_table': 'lich_su_don_hang',
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
