# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nguoidung', '0001_initial'),
        ('donhang', '0001_initial'),
        ('thuoc', '0001_initial'),
        ('benhan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsudonhang',
            name='nguoi_thay_doi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang_thay_doi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giohang',
            name='benh_nhan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gio_hang', to='nguoidung.benhnhan'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='bac_si_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang_duyet_thuoc_dac_thu', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_hang', to='nguoidung.benhnhan'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='don_thuoc',
            field=models.ForeignKey(blank=True, help_text='Toa bác sĩ (nếu bán theo đơn)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang_ban', to='benhan.donthuoc'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='nhan_vien_xu_ly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang_xu_ly', to='nguoidung.nhanvien'),
        ),
        migrations.AddField(
            model_name='chitietdonhang',
            name='chi_tiet_don_thuoc',
            field=models.ForeignKey(blank=True, help_text='Dòng toa tương ứng (nếu bán theo đơn)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_tiet_don_hang', to='benhan.chitietdonthuoc'),
        ),
        migrations.AddField(
            model_name='chitietdonhang',
            name='don_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_don_hang', to='donhang.donhang'),
        ),
        migrations.AddField(
            model_name='chitietdonhang',
            name='thuoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thuoc.thuoc'),
        ),
        migrations.AddIndex(
            model_name='thanhtoan',
            index=models.Index(fields=['don_hang'], name='thanh_toan_don_han_65e940_idx'),
        ),
        migrations.AddIndex(
            model_name='thanhtoan',
            index=models.Index(fields=['trang_thai'], name='thanh_toan_trang_t_1cb4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='thanhtoan',
            index=models.Index(fields=['ma_giao_dich'], name='thanh_toan_ma_giao_bfc528_idx'),
        ),
        migrations.AddIndex(
            model_name='thanhtoan',
            index=models.Index(fields=['ngay_thanh_toan'], name='thanh_toan_ngay_th_87eff4_idx'),
        ),
        migrations.AddIndex(
            model_name='sanphamgiohang',
            index=models.Index(fields=['gio_hang'], name='san_pham_gi_gio_han_9321aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sanphamgiohang',
            index=models.Index(fields=['thuoc'], name='san_pham_gi_thuoc_i_32f275_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sanphamgiohang',
            unique_together={('gio_hang', 'thuoc')},
        ),
        migrations.AddIndex(
            model_name='lichsudonhang',
            index=models.Index(fields=['don_hang'], name='lich_su_don_don_han_f36a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsudonhang',
            index=models.Index(fields=['thoi_gian'], name='lich_su_don_thoi_gi_587a23_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsudonhang',
            index=models.Index(fields=['trang_thai_moi'], name='lich_su_don_trang_t_8a307f_idx'),
        ),
        migrations.AddIndex(
            model_name='giohang',
            index=models.Index(fields=['benh_nhan'], name='gio_hang_benh_nh_ba0def_idx'),
        ),
        migrations.AddIndex(
            model_name='giohang',
            index=models.Index(fields=['ngay_cap_nhat'], name='gio_hang_ngay_ca_fc7026_idx'),
        ),
        migrations.AddIndex(
            model_name='donhang',
            index=models.Index(fields=['ma_don_hang'], name='don_hang_ma_don__45f17a_idx'),
        ),
        migrations.AddIndex(
            model_name='donhang',
            index=models.Index(fields=['benh_nhan', 'ngay_tao'], name='don_hang_benh_nh_ee2099_idx'),
        ),
        migrations.AddIndex(
            model_name='donhang',
            index=models.Index(fields=['trang_thai'], name='don_hang_trang_t_f61daa_idx'),
        ),
        migrations.AddIndex(
            model_name='donhang',
            index=models.Index(fields=['ngay_tao'], name='don_hang_ngay_ta_597591_idx'),
        ),
        migrations.AddIndex(
            model_name='donhang',
            index=models.Index(fields=['loai_don'], name='don_hang_loai_do_a845d9_idx'),
        ),
        migrations.AddIndex(
            model_name='chitietdonhang',
            index=models.Index(fields=['don_hang'], name='chi_tiet_do_don_han_305d89_idx'),
        ),
        migrations.AddIndex(
            model_name='chitietdonhang',
            index=models.Index(fields=['thuoc'], name='chi_tiet_do_thuoc_i_bf4f7b_idx'),
        ),
    ]
