# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loai_thong_bao', models.CharField(choices=[('LICH_HEN', 'Lịch hẹn'), ('DON_HANG', 'Đơn hàng'), ('TIN_NHAN', 'Tin nhắn mới'), ('HE_THONG', 'Hệ thống'), ('THANH_TOAN', 'Thanh toán')], max_length=20)),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('da_doc_luc', models.DateTimeField(blank=True, help_text='None = chưa đọc; có giá trị = thời điểm đọc', null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('lien_ket', models.URLField(blank=True, help_text='URL chuyển hướng khi bấm vào thông báo', max_length=500)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'thong_bao_app',
                'ordering': ['-ngay_tao'],
                'indexes': [models.Index(fields=['nguoi_nhan', 'da_doc_luc'], name='thong_bao_a_nguoi_n_42eb87_idx'), models.Index(fields=['ngay_tao'], name='thong_bao_a_ngay_ta_4327aa_idx'), models.Index(fields=['loai_thong_bao'], name='thong_bao_a_loai_th_6790f9_idx')],
            },
        ),
    ]
