# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benhan', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_dang_nhap', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('ho_ten', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10-11 số', regex='^0[0-9]{9,10}$')])),
                ('vai_tro', models.CharField(choices=[('BENH_NHAN', 'Bệnh nhân'), ('BAC_SI', 'Bác sĩ'), ('NHAN_VIEN', 'Nhân viên'), ('ADMIN', 'Quản trị viên')], db_index=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('dia_chi', models.TextField(blank=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('NAM', 'Nam'), ('NU', 'Nữ'), ('KHAC', 'Khác')], max_length=10)),
                ('cccd', models.CharField(blank=True, help_text='Căn cước công dân', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CCCD phải có 9-12 số', regex='^[0-9]{9,12}$')])),
                ('nguoi_lien_he_khan', models.CharField(blank=True, max_length=255)),
                ('sdt_lien_he_khan', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10-11 số', regex='^0[0-9]{9,10}$')])),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_device', models.CharField(blank=True, max_length=255)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Đã xác thực email/SĐT')),
                ('is_locked', models.BooleanField(default=False, help_text='Tài khoản bị khóa')),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'nguoi_dung',
            },
        ),
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bac_si', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ma_bac_si', models.CharField(db_index=True, max_length=20, unique=True)),
                ('chuyen_khoa', models.CharField(db_index=True, max_length=100)),
                ('so_giay_phep', models.CharField(max_length=50, unique=True)),
                ('trinh_do', models.CharField(choices=[('TIEN_SI', 'Tiến sĩ'), ('THAC_SI', 'Thạc sĩ'), ('BAC_SI_CK2', 'Bác sĩ chuyên khoa II'), ('BAC_SI_CK1', 'Bác sĩ chuyên khoa I'), ('BAC_SI', 'Bác sĩ'), ('Y_SI', 'Y sĩ')], default='BAC_SI', max_length=20)),
                ('chuc_vu', models.CharField(blank=True, choices=[('TRUONG_KHOA', 'Trưởng khoa'), ('PHO_KHOA', 'Phó khoa'), ('BAC_SI_CHU_NHIEM', 'Bác sĩ chủ nhiệm'), ('BAC_SI_DIEU_TRI', 'Bác sĩ điều trị'), ('BAC_SI_NOI_TRU', 'Bác sĩ nội trú'), ('THUC_TAP_SINH', 'Thực tập sinh')], max_length=30)),
                ('chuyen_mon', models.TextField(blank=True, help_text='Lĩnh vực chuyên môn sâu')),
                ('khoa_phong', models.CharField(blank=True, max_length=100)),
                ('ngay_bat_dau_cong_tac', models.DateField(blank=True, null=True)),
                ('ngay_ket_thuc_cong_tac', models.DateField(blank=True, null=True)),
                ('chung_chi', models.TextField(blank=True, help_text='Các chứng chỉ đã đạt được')),
                ('ngoai_ngu', models.CharField(blank=True, max_length=255)),
                ('lich_lam_viec', models.JSONField(blank=True, default=dict, help_text='Lịch làm việc mẫu')),
                ('gioi_thieu', models.TextField(blank=True, help_text='Giới thiệu về bác sĩ')),
                ('thanh_tich', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_working', models.BooleanField(default=True, help_text='Đang công tác')),
            ],
            options={
                'verbose_name': 'Bác sĩ',
                'verbose_name_plural': 'Bác sĩ',
                'db_table': 'bac_si',
            },
        ),
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='benh_nhan', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ma_benh_nhan', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('NAM', 'Nam'), ('NU', 'Nữ'), ('KHAC', 'Khác')], max_length=10)),
                ('dia_chi', models.TextField()),
                ('so_bao_hiem', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ngay_dang_ky_bhyt', models.DateField(blank=True, null=True)),
                ('ngay_het_han_bhyt', models.DateField(blank=True, null=True)),
                ('noi_dang_ky_kham_chua', models.CharField(blank=True, max_length=255)),
                ('nhom_mau', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('CHUA_XAC_DINH', 'Chưa xác định')], default='CHUA_XAC_DINH', max_length=15)),
                ('chieu_cao', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('can_nang', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('tien_su_benh', models.TextField(blank=True, help_text='Tiền sử bệnh lý')),
                ('tien_su_di_ung', models.TextField(blank=True, help_text='Dị ứng thuốc/thực phẩm')),
                ('benh_man_tinh', models.TextField(blank=True, help_text='Bệnh mãn tính (nếu có)')),
                ('nghe_nghiep', models.CharField(blank=True, choices=[('HOC_SINH', 'Học sinh'), ('SINH_VIEN', 'Sinh viên'), ('CAN_BO', 'Cán bộ công nhân viên'), ('KINH_DOANH', 'Kinh doanh'), ('HUU_TRI', 'Hưu trí'), ('TU_DO', 'Tự do'), ('NOI_TRO', 'Nội trợ'), ('KHAC', 'Khác')], max_length=20)),
                ('noi_lam_viec', models.CharField(blank=True, max_length=255)),
                ('tinh_trang_hon_nhan', models.CharField(blank=True, choices=[('DOC_THAN', 'Độc thân'), ('DA_KET_HON', 'Đã kết hôn'), ('LY_HON', 'Ly hôn'), ('GOA', 'Góa')], max_length=20)),
                ('ho_ten_nguoi_than', models.CharField(blank=True, max_length=255)),
                ('quan_he_nguoi_than', models.CharField(blank=True, max_length=50)),
                ('sdt_nguoi_than', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Bệnh nhân',
                'db_table': 'benh_nhan',
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loai', models.CharField(choices=[('HE_THONG', 'Hệ thống'), ('LICH_HEN', 'Lịch hẹn'), ('DON_THUOC', 'Đơn thuốc'), ('TIEM_CHUNG', 'Tiêm chủng'), ('THANH_TOAN', 'Thanh toán'), ('TAI_KHOAN', 'Tài khoản')], max_length=20)),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('du_lieu_lien_quan', models.JSONField(blank=True, default=dict)),
                ('da_xem', models.BooleanField(default=False)),
                ('ngay_xem', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'nguoidung_thong_bao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nguoi_nhan', 'da_xem'], name='nguoidung_t_nguoi_n_74478e_idx'), models.Index(fields=['loai'], name='nguoidung_t_loai_fd3bd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='NhatKyHoatDong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hanh_dong', models.CharField(choices=[('DANG_NHAP', 'Đăng nhập'), ('DANG_XUAT', 'Đăng xuất'), ('XEM', 'Xem'), ('THEM', 'Thêm'), ('SUA', 'Sửa'), ('XOA', 'Xóa'), ('THANH_TOAN', 'Thanh toán'), ('KHAC', 'Khác')], max_length=20)),
                ('doi_tuong', models.CharField(help_text='Loại đối tượng thao tác', max_length=100)),
                ('doi_tuong_id', models.CharField(blank=True, max_length=100)),
                ('du_lieu_cu', models.JSONField(blank=True, default=dict)),
                ('du_lieu_moi', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhat_ky', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'db_table': 'nhat_ky_hoat_dong',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nguoi_dung', '-created_at'], name='nhat_ky_hoa_nguoi_d_dfe98a_idx'), models.Index(fields=['hanh_dong'], name='nhat_ky_hoa_hanh_do_5d3972_idx')],
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nhan_vien', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ma_nhan_vien', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phong_ban', models.CharField(max_length=100)),
                ('chuc_vu', models.CharField(choices=[('BAN_THUOC', 'Bán thuốc'), ('DIEU_DUONG', 'Điều dưỡng'), ('LE_TAN', 'Lễ tân'), ('KHO', 'Quản lý kho'), ('KE_TOAN', 'Kế toán')], default='LE_TAN', max_length=20)),
                ('ngay_bat_dau_lam', models.DateField(blank=True, null=True)),
                ('mo_ta_cong_viec', models.TextField(blank=True)),
                ('quyen_han', models.JSONField(blank=True, default=dict, help_text='Các quyền được cấp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_working', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'nhan_vien',
                'indexes': [models.Index(fields=['ma_nhan_vien'], name='nhan_vien_ma_nhan_7c131f_idx'), models.Index(fields=['chuc_vu'], name='nhan_vien_chuc_vu_07aced_idx')],
            },
        ),
        migrations.CreateModel(
            name='LichSuKhamBenh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_kham', models.DateTimeField()),
                ('chuan_doan', models.CharField(max_length=255)),
                ('ket_luan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bac_si', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nguoidung.bacsi')),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_kham', to='nguoidung.benhnhan')),
            ],
            options={
                'verbose_name': 'Lịch sử khám bệnh',
                'verbose_name_plural': 'Lịch sử khám bệnh',
                'db_table': 'lich_su_kham_benh',
                'ordering': ['-ngay_kham'],
            },
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay', models.DateField()),
                ('gio_bat_dau', models.TimeField()),
                ('gio_ket_thuc', models.TimeField()),
                ('trang_thai', models.CharField(choices=[('RANH', 'Rảnh'), ('DA_DAT', 'Đã đặt'), ('DA_KHAM', 'Đã khám'), ('HUY', 'Đã hủy')], default='RANH', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to=settings.AUTH_USER_MODEL)),
                ('benh_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nguoidung.benhnhan')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Lịch làm việc',
                'db_table': 'lich_lam_viec',
                'ordering': ['ngay', 'gio_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='DanhGiaBacSi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Điểm từ 1-5')),
                ('nhan_xet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ho_so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benhan.hosobenhan')),
                ('bac_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='nguoidung.bacsi')),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='nguoidung.benhnhan')),
            ],
            options={
                'verbose_name': 'Đánh giá bác sĩ',
                'verbose_name_plural': 'Đánh giá bác sĩ',
                'db_table': 'danh_gia_bac_si',
            },
        ),
        migrations.AddIndex(
            model_name='benhnhan',
            index=models.Index(fields=['ma_benh_nhan'], name='benh_nhan_ma_benh_c22b59_idx'),
        ),
        migrations.AddIndex(
            model_name='benhnhan',
            index=models.Index(fields=['so_bao_hiem'], name='benh_nhan_so_bao__7d6003_idx'),
        ),
        migrations.AddIndex(
            model_name='benhnhan',
            index=models.Index(fields=['ngay_sinh'], name='benh_nhan_ngay_si_26e32f_idx'),
        ),
        migrations.AddIndex(
            model_name='bacsi',
            index=models.Index(fields=['ma_bac_si'], name='bac_si_ma_bac__5fa19a_idx'),
        ),
        migrations.AddIndex(
            model_name='bacsi',
            index=models.Index(fields=['chuyen_khoa'], name='bac_si_chuyen__ea4d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='bacsi',
            index=models.Index(fields=['so_giay_phep'], name='bac_si_so_giay_257963_idx'),
        ),
        migrations.AddIndex(
            model_name='nguoidung',
            index=models.Index(fields=['email'], name='nguoi_dung_email_d26f14_idx'),
        ),
        migrations.AddIndex(
            model_name='nguoidung',
            index=models.Index(fields=['so_dien_thoai'], name='nguoi_dung_so_dien_c4d302_idx'),
        ),
        migrations.AddIndex(
            model_name='nguoidung',
            index=models.Index(fields=['vai_tro'], name='nguoi_dung_vai_tro_2cfd10_idx'),
        ),
        migrations.AddIndex(
            model_name='nguoidung',
            index=models.Index(fields=['is_active'], name='nguoi_dung_is_acti_caf296_idx'),
        ),
        migrations.AddIndex(
            model_name='nguoidung',
            index=models.Index(fields=['cccd'], name='nguoi_dung_cccd_283c75_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsukhambenh',
            index=models.Index(fields=['benh_nhan', 'ngay_kham'], name='lich_su_kha_benh_nh_9ff87d_idx'),
        ),
        migrations.AddIndex(
            model_name='lichlamviec',
            index=models.Index(fields=['nguoi_dung', 'ngay'], name='lich_lam_vi_nguoi_d_6f7359_idx'),
        ),
        migrations.AddIndex(
            model_name='lichlamviec',
            index=models.Index(fields=['trang_thai'], name='lich_lam_vi_trang_t_0648dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lichlamviec',
            unique_together={('nguoi_dung', 'ngay', 'gio_bat_dau')},
        ),
        migrations.AddIndex(
            model_name='danhgiabacsi',
            index=models.Index(fields=['bac_si', 'diem'], name='danh_gia_ba_bac_si__643d43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='danhgiabacsi',
            unique_together={('benh_nhan', 'bac_si', 'ho_so')},
        ),
    ]
