# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('ten_bao_cao', models.CharField(max_length=255)),
                ('loai', models.CharField(choices=[('DOANH_THU', 'Doanh thu'), ('BENH_NHAN', 'Bệnh nhân'), ('THUOC', 'Thuốc'), ('VACCINE', 'Vaccine'), ('LICH_HEN', 'Lịch hẹn'), ('KHAC', 'Khác')], max_length=20)),
                ('thoi_gian_bat_dau', models.DateField()),
                ('thoi_gian_ket_thuc', models.DateField()),
                ('du_lieu', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'db_table': 'bao_cao',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='MauBaoCao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('ten_mau', models.CharField(max_length=255)),
                ('loai_bao_cao', models.CharField(choices=[('DOANH_THU', 'Doanh thu'), ('BENH_NHAN', 'Bệnh nhân'), ('THUOC', 'Thuốc'), ('VACCINE', 'Vaccine'), ('LICH_HEN', 'Lịch hẹn'), ('KHAC', 'Khác')], max_length=20)),
                ('tham_so', models.JSONField(default=dict, help_text='Các tham số mặc định cho báo cáo')),
                ('mo_ta', models.TextField(blank=True)),
                ('la_cong_khai', models.BooleanField(default=False, help_text='True = mọi người có thể dùng mẫu này')),
            ],
            options={
                'verbose_name': 'Mẫu báo cáo',
                'verbose_name_plural': 'Mẫu báo cáo',
                'db_table': 'mau_bao_cao',
            },
        ),
    ]
