# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baocao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maubaocao',
            name='nguoi_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mau_bao_cao_da_tao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baocao',
            name='nguoi_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bao_cao_da_tao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='maubaocao',
            index=models.Index(fields=['loai_bao_cao'], name='mau_bao_cao_loai_ba_f40699_idx'),
        ),
        migrations.AddIndex(
            model_name='maubaocao',
            index=models.Index(fields=['la_cong_khai'], name='mau_bao_cao_la_cong_afe986_idx'),
        ),
        migrations.AddIndex(
            model_name='baocao',
            index=models.Index(fields=['loai', 'ngay_tao'], name='bao_cao_loai_c7dd39_idx'),
        ),
        migrations.AddIndex(
            model_name='baocao',
            index=models.Index(fields=['thoi_gian_bat_dau', 'thoi_gian_ket_thuc'], name='bao_cao_thoi_gi_9cfe56_idx'),
        ),
    ]
