# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGiaDichVu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('nhan_xet', models.TextField(blank=True)),
                ('thai_do_nhan_vien', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('thoi_gian_cho', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('chat_luong_dich_vu', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('co_so_vat_chat', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đánh giá dịch vụ',
                'verbose_name_plural': 'Đánh giá dịch vụ',
                'db_table': 'danh_gia_dich_vu',
            },
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_lich_hen', models.CharField(blank=True, max_length=20, unique=True)),
                ('loai_lich', models.CharField(choices=[('KHAM_BENH', 'Khám bệnh'), ('TIEM_CHUNG', 'Tiêm chủng'), ('TAI_KHAM', 'Tái khám'), ('TU_VAN', 'Tư vấn')], max_length=20)),
                ('ngay_gio_hen', models.DateTimeField()),
                ('ngay_gio_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_DAT', 'Đã đặt'), ('DA_XAC_NHAN', 'Đã xác nhận'), ('CHECKED_IN', 'Đã check-in / chờ vào phòng'), ('DANG_KHAM', 'Đang khám'), ('HOAN_THANH', 'Hoàn thành'), ('DA_HUY', 'Đã hủy'), ('VANG_MAT', 'Vắng mặt'), ('QUA_HAN', 'Quá hạn')], default='CHO_XAC_NHAN', max_length=20)),
                ('so_dien_thoai_lien_he', models.CharField(blank=True, max_length=15)),
                ('email_lien_he', models.EmailField(blank=True, max_length=254)),
                ('can_nhac_nho', models.BooleanField(default=True)),
                ('da_nhac_nho', models.BooleanField(default=False)),
                ('ngay_nhac_nho', models.DateTimeField(blank=True, null=True)),
                ('ly_do_huy', models.TextField(blank=True)),
                ('ngay_huy', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_den', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('gia_dich_vu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('phuong_thuc_thanh_toan', models.CharField(blank=True, max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('ma_phong', models.CharField(blank=True, default='', help_text='Mã phòng khám (VD: P01)', max_length=30)),
                ('ten_phong', models.CharField(blank=True, default='', help_text='Tên phòng hiển thị', max_length=100)),
                ('stt_trong_ngay', models.PositiveIntegerField(blank=True, help_text='Số thứ tự tiếp nhận trong ngày (walk-in / hàng chờ)', null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'db_table': 'lich_hen',
                'ordering': ['-ngay_gio_hen'],
            },
        ),
        migrations.CreateModel(
            name='LichKham',
            fields=[
                ('lich_hen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lich_kham', serialize=False, to='lichhen.lichhen')),
                ('ly_do_kham', models.TextField()),
                ('trieu_chung', models.TextField()),
                ('chuan_doan_so_bo', models.TextField(blank=True)),
                ('ket_luan', models.TextField(blank=True)),
                ('loi_khuyen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch khám',
                'verbose_name_plural': 'Lịch khám',
                'db_table': 'lich_kham',
            },
        ),
        migrations.CreateModel(
            name='LichTiem',
            fields=[
                ('lich_hen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lich_tiem', serialize=False, to='lichhen.lichhen')),
                ('so_mui', models.IntegerField(default=1)),
                ('lo_vaccine', models.CharField(blank=True, max_length=100)),
                ('nha_san_xuat', models.CharField(blank=True, max_length=255)),
                ('han_su_dung', models.DateField(blank=True, null=True)),
                ('ngay_tiem_thuc_te', models.DateTimeField(blank=True, null=True)),
                ('phan_ung_sau_tiem', models.TextField(blank=True)),
                ('xu_tri_phan_ung', models.TextField(blank=True)),
                ('trang_thai_tiem', models.CharField(choices=[('CHUA_TIEM', 'Chưa tiêm'), ('DA_TIEM', 'Đã tiêm'), ('TAM_HOAN', 'Tạm hoãn'), ('CHONG_CHI_DINH', 'Chống chỉ định')], default='CHUA_TIEM', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch tiêm',
                'verbose_name_plural': 'Lịch tiêm',
                'db_table': 'lich_tiem',
            },
        ),
        migrations.CreateModel(
            name='NhacNhoLichHen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loai_nhac', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push notification'), ('ZALO', 'Zalo')], max_length=10)),
                ('thoi_gian_nhac', models.DateTimeField()),
                ('noi_dung', models.TextField()),
                ('trang_thai', models.CharField(choices=[('CHO_GUI', 'Chờ gửi'), ('DA_GUI', 'Đã gửi'), ('THAT_BAI', 'Thất bại')], default='CHO_GUI', max_length=20)),
                ('chi_tiet_phan_hoi', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhac_nho', to='lichhen.lichhen')),
            ],
            options={
                'verbose_name': 'Nhắc nhở lịch hẹn',
                'verbose_name_plural': 'Nhắc nhở lịch hẹn',
                'db_table': 'nhac_nho_lich_hen',
            },
        ),
        migrations.CreateModel(
            name='LichSuLichHen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trang_thai_cu', models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_DAT', 'Đã đặt'), ('DA_XAC_NHAN', 'Đã xác nhận'), ('CHECKED_IN', 'Đã check-in / chờ vào phòng'), ('DANG_KHAM', 'Đang khám'), ('HOAN_THANH', 'Hoàn thành'), ('DA_HUY', 'Đã hủy'), ('VANG_MAT', 'Vắng mặt'), ('QUA_HAN', 'Quá hạn')], max_length=20)),
                ('trang_thai_moi', models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_DAT', 'Đã đặt'), ('DA_XAC_NHAN', 'Đã xác nhận'), ('CHECKED_IN', 'Đã check-in / chờ vào phòng'), ('DANG_KHAM', 'Đang khám'), ('HOAN_THANH', 'Hoàn thành'), ('DA_HUY', 'Đã hủy'), ('VANG_MAT', 'Vắng mặt'), ('QUA_HAN', 'Quá hạn')], max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lich_hen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='lichhen.lichhen')),
            ],
            options={
                'verbose_name': 'Lịch sử lịch hẹn',
                'verbose_name_plural': 'Lịch sử lịch hẹn',
                'db_table': 'lich_su_lich_hen',
                'ordering': ['-created_at'],
            },
        ),
    ]
