# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nguoidung', '0001_initial'),
        ('thuoc', '0001_initial'),
        ('lichhen', '0001_initial'),
        ('benhan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsulichhen',
            name='nguoi_thay_doi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_thay_doi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='bac_si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_hen_schedule', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen_appointments', to='nguoidung.benhnhan'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='nguoi_huy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_hen_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='nhan_vien_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_hen_created', to='nguoidung.nhanvien'),
        ),
        migrations.AddField(
            model_name='danhgiadichvu',
            name='lich_hen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='lichhen.lichhen'),
        ),
        migrations.AddIndex(
            model_name='nhacnholichhen',
            index=models.Index(fields=['thoi_gian_nhac', 'trang_thai'], name='nhac_nho_li_thoi_gi_aed3a2_idx'),
        ),
        migrations.AddField(
            model_name='lichtiem',
            name='nguoi_tiem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_tiem_performed', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='lichtiem',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_tiem_vaccine_schedule', to='thuoc.vaccine'),
        ),
        migrations.AddField(
            model_name='lichkham',
            name='bac_si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_kham_consultations', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='lichkham',
            name='ho_so_benh_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_kham', to='benhan.hosobenhan'),
        ),
        migrations.AddIndex(
            model_name='lichhen',
            index=models.Index(fields=['benh_nhan', 'ngay_gio_hen'], name='lich_hen_benh_nh_645d73_idx'),
        ),
        migrations.AddIndex(
            model_name='lichhen',
            index=models.Index(fields=['bac_si', 'ngay_gio_hen'], name='lich_hen_bac_si__d03e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='lichhen',
            index=models.Index(fields=['trang_thai'], name='lich_hen_trang_t_427877_idx'),
        ),
        migrations.AddIndex(
            model_name='lichhen',
            index=models.Index(fields=['ngay_gio_hen'], name='lich_hen_ngay_gi_c4a047_idx'),
        ),
        migrations.AddIndex(
            model_name='lichhen',
            index=models.Index(fields=['loai_lich'], name='lich_hen_loai_li_22bf7e_idx'),
        ),
    ]
