# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_don_vi', models.CharField(max_length=50, unique=True)),
                ('ky_hieu', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Đơn vị tính',
                'db_table': 'don_vi_tinh',
                'ordering': ['ten_don_vi'],
            },
        ),
        migrations.CreateModel(
            name='LoaiThuoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Loại thuốc',
                'verbose_name_plural': 'Loại thuốc',
                'db_table': 'loai_thuoc',
                'ordering': ['ten_loai'],
            },
        ),
        migrations.CreateModel(
            name='LoaiVaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Loại vaccine',
                'verbose_name_plural': 'Loại vaccine',
                'db_table': 'loai_vaccine',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_ncc', models.CharField(max_length=50, unique=True)),
                ('ten_ncc', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ma_so_thue', models.CharField(blank=True, max_length=20)),
                ('nguoi_lien_he', models.CharField(blank=True, max_length=100)),
                ('ghi_chu', models.TextField(blank=True)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'db_table': 'nha_cung_cap',
                'ordering': ['ten_ncc'],
            },
        ),
        migrations.CreateModel(
            name='Thuoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_thuoc', models.CharField(max_length=50, unique=True)),
                ('ten_thuoc', models.CharField(max_length=255)),
                ('don_gia_nhap', models.DecimalField(decimal_places=2, help_text='Giá nhập vào', max_digits=10)),
                ('ty_le_ke_khai', models.DecimalField(decimal_places=2, default=0, help_text='Tỷ lệ kê khai (%)', max_digits=5)),
                ('gia_ban', models.DecimalField(decimal_places=2, help_text='Giá bán lẻ', max_digits=10)),
                ('nha_san_xuat', models.CharField(blank=True, default='', max_length=255)),
                ('nuoc_san_xuat', models.CharField(blank=True, default='', max_length=100)),
                ('thanh_phan', models.TextField(blank=True, help_text='Thành phần chính')),
                ('ham_luong', models.CharField(blank=True, help_text='Hàm lượng (VD: 500mg)', max_length=100)),
                ('cach_dung', models.TextField(blank=True)),
                ('chi_dinh', models.TextField(blank=True)),
                ('chong_chi_dinh', models.TextField(blank=True)),
                ('tac_dung_phu', models.TextField(blank=True)),
                ('can_don_thuoc', models.BooleanField(default=False)),
                ('can_tu_van', models.BooleanField(default=False)),
                ('la_thuoc_ban_chay', models.BooleanField(default=False)),
                ('mo_ta', models.TextField(blank=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='thuoc/')),
                ('trang_thai', models.BooleanField(default=True, help_text='True: đang kinh doanh, False: ngừng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thuoc', to='thuoc.donvitinh')),
                ('loai_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thuoc', to='thuoc.loaithuoc')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
                'db_table': 'thuoc',
                'ordering': ['ten_thuoc'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_vaccine', models.CharField(max_length=50, unique=True)),
                ('ten_vaccine', models.CharField(max_length=255)),
                ('gia_nhap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_tiem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phong_benh', models.CharField(help_text='Phòng bệnh gì', max_length=255)),
                ('do_tuoi_ap_dung', models.CharField(max_length=100)),
                ('so_mui', models.IntegerField(default=1)),
                ('lich_tiem', models.TextField(blank=True, help_text='Lịch tiêm chi tiết')),
                ('khoang_cach_mui', models.IntegerField(blank=True, help_text='Khoảng cách giữa các mũi (ngày)', null=True)),
                ('bao_quan', models.CharField(blank=True, help_text='Nhiệt độ bảo quản', max_length=255)),
                ('han_su_dung', models.DateField(blank=True, null=True)),
                ('nha_san_xuat', models.CharField(blank=True, default='', max_length=255)),
                ('nuoc_san_xuat', models.CharField(blank=True, default='', max_length=100)),
                ('thanh_phan', models.TextField(blank=True)),
                ('chong_chi_dinh', models.TextField(blank=True)),
                ('phan_ung_sau_tiem', models.TextField(blank=True, help_text='Phản ứng sau tiêm')),
                ('mo_ta', models.TextField(blank=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='vaccine/')),
                ('trang_thai', models.BooleanField(default=True)),
                ('la_vaccine_dich_vu', models.BooleanField(default=False, help_text='Vaccine dịch vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loai_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine', to='thuoc.loaivaccine')),
                ('nha_cung_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine', to='thuoc.nhacungcap')),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccine',
                'db_table': 'vaccine',
                'ordering': ['ten_vaccine'],
            },
        ),
        migrations.CreateModel(
            name='ToaThuocMau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_toa', models.CharField(max_length=50, unique=True)),
                ('ten_toa', models.CharField(max_length=255)),
                ('chuan_doan', models.TextField(help_text='Chẩn đoán áp dụng')),
                ('trieu_chung', models.TextField(blank=True)),
                ('ghi_chu', models.TextField(blank=True)),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thuoc_chi_tiet_toa_mau', to='thuoc.thuoc')),
            ],
            options={
                'verbose_name': 'Toa thuốc mẫu',
                'verbose_name_plural': 'Toa thuốc mẫu',
                'db_table': 'thuoc_toa_thuoc_mau',
            },
        ),
        migrations.CreateModel(
            name='ThuocNhaCungCap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gia_cung_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('la_ncc_chinh', models.BooleanField(default=False)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuoc.nhacungcap')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuoc.thuoc')),
            ],
            options={
                'db_table': 'thuoc_nha_cung_cap',
            },
        ),
        migrations.AddField(
            model_name='thuoc',
            name='nha_cung_cap',
            field=models.ManyToManyField(blank=True, through='thuoc.ThuocNhaCungCap', to='thuoc.nhacungcap'),
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('loai_nhap', models.CharField(choices=[('THUOC', 'Thuốc'), ('VACCINE', 'Vaccine')], max_length=10)),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('ngay_chung_tu', models.DateField()),
                ('so_chung_tu', models.CharField(blank=True, max_length=100)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('da_duyet_chi', models.BooleanField(default=False)),
                ('nguoi_duyet_chi', models.CharField(blank=True, max_length=150)),
                ('ngay_duyet_chi', models.DateTimeField(blank=True, null=True)),
                ('da_cap_nhat_kho', models.BooleanField(default=False)),
                ('nguoi_nhap', models.CharField(max_length=100)),
                ('ghi_chu', models.TextField(blank=True)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thuoc.nhacungcap')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'db_table': 'phieu_nhap_kho',
                'ordering': ['-ngay_nhap'],
            },
        ),
        migrations.CreateModel(
            name='LichSuGiaVaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gia_cu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_moi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngay_thay_doi', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thay_doi', models.CharField(max_length=100)),
                ('ly_do', models.TextField(blank=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_gia', to='thuoc.vaccine')),
            ],
            options={
                'verbose_name': 'Lịch sử giá vaccine',
                'verbose_name_plural': 'Lịch sử giá vaccine',
                'db_table': 'lich_su_gia_vaccine',
                'ordering': ['-ngay_thay_doi'],
            },
        ),
        migrations.CreateModel(
            name='LichSuGiaThuoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gia_cu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_moi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngay_thay_doi', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thay_doi', models.CharField(max_length=100)),
                ('ly_do', models.TextField(blank=True)),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_gia', to='thuoc.thuoc')),
            ],
            options={
                'verbose_name': 'Lịch sử giá thuốc',
                'verbose_name_plural': 'Lịch sử giá thuốc',
                'db_table': 'lich_su_gia_thuoc',
                'ordering': ['-ngay_thay_doi'],
            },
        ),
        migrations.CreateModel(
            name='KhoVaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('so_luong', models.IntegerField(default=0)),
                ('ngay_nhap', models.DateField()),
                ('han_su_dung', models.DateField()),
                ('lo_sx', models.CharField(blank=True, max_length=100, verbose_name='Lô sản xuất')),
                ('vi_tri', models.CharField(blank=True, max_length=100)),
                ('ghi_chu', models.TextField(blank=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kho_vaccine', to='thuoc.vaccine')),
            ],
            options={
                'verbose_name': 'Kho vaccine',
                'verbose_name_plural': 'Kho vaccine',
                'db_table': 'kho_vaccine',
                'ordering': ['-ngay_nhap'],
            },
        ),
        migrations.CreateModel(
            name='KhoThuoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('so_luong', models.IntegerField(default=0)),
                ('ngay_nhap', models.DateField()),
                ('han_su_dung', models.DateField()),
                ('lo_sx', models.CharField(blank=True, max_length=100, verbose_name='Lô sản xuất')),
                ('vi_tri', models.CharField(blank=True, help_text='Vị trí lưu kho', max_length=100)),
                ('ghi_chu', models.TextField(blank=True)),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kho_thuoc', to='thuoc.thuoc')),
            ],
            options={
                'verbose_name': 'Kho thuốc',
                'verbose_name_plural': 'Kho thuốc',
                'db_table': 'kho_thuoc',
                'ordering': ['-ngay_nhap'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietToaMau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lieu_luong', models.CharField(max_length=100)),
                ('so_luong', models.IntegerField(default=1)),
                ('cach_dung', models.CharField(blank=True, max_length=255)),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thuoc.thuoc')),
                ('toa_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='thuoc.toathuocmau')),
            ],
            options={
                'db_table': 'thuoc_chi_tiet_toa_mau',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhapVaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('han_su_dung', models.DateField()),
                ('lo_sx', models.CharField(blank=True, max_length=100)),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_vaccine', to='thuoc.phieunhapkho')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thuoc.vaccine')),
            ],
            options={
                'db_table': 'chi_tiet_phieu_nhap_vaccine',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhapThuoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('han_su_dung', models.DateField()),
                ('lo_sx', models.CharField(blank=True, max_length=100)),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_thuoc', to='thuoc.phieunhapkho')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thuoc.thuoc')),
            ],
            options={
                'db_table': 'chi_tiet_phieu_nhap_thuoc',
            },
        ),
        migrations.AddIndex(
            model_name='vaccine',
            index=models.Index(fields=['ma_vaccine'], name='vaccine_ma_vacc_9d002f_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccine',
            index=models.Index(fields=['ten_vaccine'], name='vaccine_ten_vac_5b5bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccine',
            index=models.Index(fields=['loai_vaccine'], name='vaccine_loai_va_1af6c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thuocnhacungcap',
            unique_together={('thuoc', 'nha_cung_cap')},
        ),
        migrations.AddIndex(
            model_name='thuoc',
            index=models.Index(fields=['ma_thuoc'], name='thuoc_ma_thuo_31e3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='thuoc',
            index=models.Index(fields=['ten_thuoc'], name='thuoc_ten_thu_ee2920_idx'),
        ),
        migrations.AddIndex(
            model_name='thuoc',
            index=models.Index(fields=['loai_thuoc'], name='thuoc_loai_th_36bf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='thuoc',
            index=models.Index(fields=['trang_thai'], name='thuoc_trang_t_8a3ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='khovaccine',
            index=models.Index(fields=['han_su_dung'], name='kho_vaccine_han_su__408878_idx'),
        ),
        migrations.AddIndex(
            model_name='khothuoc',
            index=models.Index(fields=['han_su_dung'], name='kho_thuoc_han_su__274b20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chitiettoamau',
            unique_together={('toa_thuoc', 'thuoc')},
        ),
    ]
