# Generated by Django 4.2.29 on 2026-04-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benhan', '0001_initial'),
        ('nguoidung', '0001_initial'),
        ('thuoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toathuocmau',
            name='bac_si_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benhan_toa_thuoc_mau', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='theodoidieutri',
            name='bac_si',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theo_doi_dieu_tri', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='theodoidieutri',
            name='ho_so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi', to='benhan.hosobenhan'),
        ),
        migrations.AddField(
            model_name='phieuxuatthuoc',
            name='don_thuoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_xuat', to='benhan.donthuoc'),
        ),
        migrations.AddField(
            model_name='phieuxuatthuoc',
            name='nguoi_xuat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_xuat', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='lichsutiemchung',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_tiem', to='nguoidung.benhnhan'),
        ),
        migrations.AddField(
            model_name='lichsutiemchung',
            name='nguoi_tiem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_tiem', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='lichsutiemchung',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_su_tiem', to='thuoc.vaccine'),
        ),
        migrations.AddField(
            model_name='lichhentaikham',
            name='bac_si',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_hen_taikham', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='lichhentaikham',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen_taikham', to='nguoidung.benhnhan'),
        ),
        migrations.AddField(
            model_name='lichhentaikham',
            name='ho_so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='benhan.hosobenhan'),
        ),
        migrations.AddField(
            model_name='hosobenhan',
            name='bac_si',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ho_so_kham', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='hosobenhan',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so', to='nguoidung.benhnhan'),
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='bac_si',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_thuoc', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_thuoc', to='nguoidung.benhnhan'),
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='ho_so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_thuoc', to='benhan.hosobenhan'),
        ),
        migrations.AddField(
            model_name='chitietxuatthuoc',
            name='kho_thuoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thuoc.khothuoc'),
        ),
        migrations.AddField(
            model_name='chitietxuatthuoc',
            name='phieu_xuat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='benhan.phieuxuatthuoc'),
        ),
        migrations.AddField(
            model_name='chitiettoamau',
            name='thuoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benhan_chitiet_toamau', to='thuoc.thuoc'),
        ),
        migrations.AddField(
            model_name='chitiettoamau',
            name='toa_thuoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='benhan.toathuocmau'),
        ),
        migrations.AddField(
            model_name='chitietdonthuoc',
            name='don_thuoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_don_thuoc', to='benhan.donthuoc'),
        ),
        migrations.AddField(
            model_name='chitietdonthuoc',
            name='thuoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benhan_chitiet_donthuoc', to='thuoc.thuoc'),
        ),
        migrations.AddField(
            model_name='chandoan',
            name='bac_si_chan_doan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chan_doan', to='nguoidung.bacsi'),
        ),
        migrations.AddField(
            model_name='chandoan',
            name='ho_so',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chan_doan', to='benhan.hosobenhan'),
        ),
        migrations.AddIndex(
            model_name='lichsutiemchung',
            index=models.Index(fields=['benh_nhan', 'ngay_tiem'], name='lich_su_tie_benh_nh_344496_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsutiemchung',
            index=models.Index(fields=['ngay_tiem_tiep_theo'], name='lich_su_tie_ngay_ti_fdc9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsutiemchung',
            index=models.Index(fields=['vaccine'], name='lich_su_tie_vaccine_d26881_idx'),
        ),
        migrations.AddIndex(
            model_name='lichhentaikham',
            index=models.Index(fields=['ngay_hen', 'trang_thai'], name='lich_hen_ta_ngay_he_ab063e_idx'),
        ),
        migrations.AddIndex(
            model_name='lichhentaikham',
            index=models.Index(fields=['benh_nhan', 'ngay_hen'], name='lich_hen_ta_benh_nh_129be6_idx'),
        ),
        migrations.AddIndex(
            model_name='hosobenhan',
            index=models.Index(fields=['benh_nhan', 'ngay_kham'], name='ho_so_benh__benh_nh_04606b_idx'),
        ),
        migrations.AddIndex(
            model_name='hosobenhan',
            index=models.Index(fields=['bac_si', 'ngay_kham'], name='ho_so_benh__bac_si__20aa59_idx'),
        ),
        migrations.AddIndex(
            model_name='hosobenhan',
            index=models.Index(fields=['trang_thai'], name='ho_so_benh__trang_t_d2085c_idx'),
        ),
        migrations.AddIndex(
            model_name='hosobenhan',
            index=models.Index(fields=['ma_hs'], name='ho_so_benh__ma_hs_ffa916_idx'),
        ),
        migrations.AddIndex(
            model_name='donthuoc',
            index=models.Index(fields=['trang_thai'], name='don_thuoc_trang_t_e00ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='donthuoc',
            index=models.Index(fields=['benh_nhan', 'ngay_tao'], name='don_thuoc_benh_nh_290016_idx'),
        ),
        migrations.AddIndex(
            model_name='donthuoc',
            index=models.Index(fields=['ma_don'], name='don_thuoc_ma_don_d6527e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chitiettoamau',
            unique_together={('toa_thuoc', 'thuoc')},
        ),
        migrations.AddIndex(
            model_name='chitietdonthuoc',
            index=models.Index(fields=['don_thuoc', 'thuoc'], name='chi_tiet_do_don_thu_cc3761_idx'),
        ),
        migrations.AddIndex(
            model_name='chandoan',
            index=models.Index(fields=['ma_icd10'], name='chan_doan_ma_icd1_6cfce8_idx'),
        ),
        migrations.AddIndex(
            model_name='chandoan',
            index=models.Index(fields=['ten_benh'], name='chan_doan_ten_ben_bd680b_idx'),
        ),
    ]
